// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using resep_langkah.Data;

#nullable disable

namespace resep_langkah.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("resep_langkah.Models.Langkah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentLangkahId")
                        .HasColumnType("integer");

                    b.Property<int>("ResepId")
                        .HasColumnType("integer");

                    b.Property<int>("Urutan")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentLangkahId");

                    b.HasIndex("ResepId");

                    b.ToTable("Langkah");
                });

            modelBuilder.Entity("resep_langkah.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LangkahId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nilai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipeData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LangkahId");

                    b.ToTable("Parameter");
                });

            modelBuilder.Entity("resep_langkah.Models.Resep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resep");
                });

            modelBuilder.Entity("resep_langkah.Models.Langkah", b =>
                {
                    b.HasOne("resep_langkah.Models.Langkah", "ParentLangkah")
                        .WithMany("SubLangkahs")
                        .HasForeignKey("ParentLangkahId");

                    b.HasOne("resep_langkah.Models.Resep", "Resep")
                        .WithMany("Langkahs")
                        .HasForeignKey("ResepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentLangkah");

                    b.Navigation("Resep");
                });

            modelBuilder.Entity("resep_langkah.Models.Parameter", b =>
                {
                    b.HasOne("resep_langkah.Models.Langkah", "Langkah")
                        .WithMany("Parameters")
                        .HasForeignKey("LangkahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Langkah");
                });

            modelBuilder.Entity("resep_langkah.Models.Langkah", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("SubLangkahs");
                });

            modelBuilder.Entity("resep_langkah.Models.Resep", b =>
                {
                    b.Navigation("Langkahs");
                });
#pragma warning restore 612, 618
        }
    }
}
